name: tabriklar
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# NOTE: update chiqaishdan oldin test reklamani o'chirish kerak
version: 1.0.15+17

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  provider: ^6.0.2
  flutter_advanced_drawer: ^1.3.0
  share_plus: ^10.1.4


  cached_network_image:

  flutter_native_splash: ^2.4.1
  firebase_database: ^12.1.0
  firebase_core: ^4.2.1

  firebase_core_platform_interface: ^6.0.2
  easy_localization:



  logging: ^1.1.0
  flutter_screenutil: ^5.9.3
  file: ^6.1.4

  http: ^1.4.0
  path_provider: ^2.0.10
  flutter_easyloading: ^3.0.5
  logger: ^1.1.0
  curved_navigation_bar: ^1.0.1
  connectivity_plus: ^6.0.3
  flutter_staggered_animations: ^1.1.1
  shimmer: ^2.0.0
  google_mobile_ads: ^5.3.1
  url_launcher: ^6.1.10

#  app_version_update:
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  get_it:
  package_info_plus:
  permission_handler:
  intl:
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.3.0
  json_annotation:
  freezed_annotation:
  freezed:
  formz:
  bloc:
  flutter_bloc:
  flutter_svg:
  flutter_touch_ripple: ^1.1.21
  top_snackbar_flutter: ^3.1.0
  firebase_remote_config: ^6.1.2
  firebase_analytics: ^12.0.4
  rate_my_app: ^2.3.1
  flutter_painter_v2: ^2.1.0+1
  social_share:
    git:
      url: https://github.com/AbbosMamadaliyev/social_share.git
  widgets_to_image: ^1.0.0
  geolocator: ^13.0.2




dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/happy.db
    - assets/ru_happy.db
    - assets/en_happy.db
    - assets/images/
    - assets/icons/
    - assets/translations/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


